#!/bin/bash
set -e

echo "Welcome to the Drupal DDEV Site Installer"
echo "----------------------------------------"

read -r -p "Site name: " SITE_NAME
if [[ -z "$SITE_NAME" ]]; then
    echo "Site name cannot be empty. Exiting."
    exit 1
fi

# Generate a safe default directory name
DIR_NAME=$(echo "$SITE_NAME" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9]/-/g' -e 's/-\+/-/g' -e 's/^-//' -e 's/-$//')
read -r -p "Project directory name [default: $DIR_NAME]: " USER_DIR_NAME
DIR_NAME=${USER_DIR_NAME:-$DIR_NAME}

echo "----------------------------------------"

# Ask for Drupal version
echo "Which version would you like to install?"
echo "1) Drupal 11"
echo "2) Drupal CMS"
read -r -p "Select option (1 or 2): " version_choice

if [[ "$version_choice" == "1" ]]; then
    PACKAGE="drupal/recommended-project:^11"
elif [[ "$version_choice" == "2" ]]; then
    PACKAGE="drupal/cms"
else
    echo "Invalid option. Exiting."
    exit 1
fi

# Ask for Project path (web)
read -r -p "Project path (docroot) [default: web]: " DOCROOT
DOCROOT=${DOCROOT:-web}

echo "----------------------------------------"
echo "Starting installation..."

echo "Creating Drupal root directory '${DIR_NAME}' and entering it..."
mkdir -p "$DIR_NAME"
cd "$DIR_NAME"

echo "Configuring DDEV project..."
ddev config --project-name="$DIR_NAME" --project-type=drupal11 --docroot="$DOCROOT"

echo "Starting DDEV..."
ddev start

echo "Installing Drupal via Composer ($PACKAGE)..."
ddev composer create-project -y "$PACKAGE"

echo "Creating .gitignore..."
cat << EOF > .gitignore
# Ignore directories generated by Composer
/vendor/

# Ignore Drupal core and contrib files
/${DOCROOT}/core/
/${DOCROOT}/modules/contrib/
/${DOCROOT}/themes/contrib/
/${DOCROOT}/profiles/contrib/
/${DOCROOT}/libraries/

# Ignore sensitive configuration files
/${DOCROOT}/sites/*/settings*.php
/${DOCROOT}/sites/*/services*.yml
/${DOCROOT}/sites/*/files/

# DDEV
# Note: DDEV manages its own .gitignore inside the .ddev folder for things like db snapshots.
# We commit the .ddev folder to version control so the team shares the same environment.
.ddev/.env

# IDEs and OS files
.idea/
.vscode/
.DS_Store
*.swp
EOF

echo "Requiring Drush..."
ddev composer require drush/drush

echo "Running Drupal installation..."
ddev drush site:install --site-name="$SITE_NAME" --account-name=admin --account-pass=admin -y

echo "----------------------------------------"
echo "Installation complete! Your site should now be ready."
ddev launch
